=== riciPrini/Internship-project/MATSim/mappe_MATSIM/dtd/cameras.dtd
<!ELEMENT perception (cameras, parkings) >

<!ELEMENT cameras (camera*)>
<!ATTLIST cameras all CDATA #IMPLIED class CDATA #IMPLIED >

<!ELEMENT parkings (camera*)>
<!ATTLIST parkings all CDATA #IMPLIED class CDATA #IMPLIED >

<!ELEMENT camera EMPTY>
<!ATTLIST camera class CDATA #REQUIRED id ID #REQUIRED link CDATA #IMPLIED park CDATA #IMPLIED>

=== riciPrini/Internship-project/MATSim/agenti/mappe_matsim/1k/cameras.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE perception SYSTEM "./dtd/cameras.dtd">
<perception>
	<!-- <cameras all="false">
/		<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camerauno" link="1" />
	</cameras> -->
	
<cameras all="false">
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera0" link="1"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera1" link="10"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera2" link="100"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera3" link="1000"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera4" link="1001"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera5" link="1002"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera6" link="1003"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera7" link="1004"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera8" link="1005"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera9" link="1006"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera10" link="1007"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera11" link="1008"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera12" link="1009"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera13" link="101"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera14" link="1010"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera15" link="1011"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera16" link="1012"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera17" link="1013"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera18" link="1014"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera19" link="1015"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera20" link="1016"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera21" link="1018"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera22" link="1019"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera23" link="102"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera24" link="1020"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera25" link="1021"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera26" link="1022"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera27" link="1023"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera28" link="1024"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera29" link="1025"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera30" link="1026"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera31" link="1027"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera32" link="1028"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera33" link="1029"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera34" link="103"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera35" link="1030"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera36" link="1031"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera37" link="1032"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera38" link="1033"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera39" link="1034"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera40" link="1035"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera41" link="1036"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera42" link="1037"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera43" link="1038"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera44" link="1039"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera45" link="104"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera46" link="1040"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera47" link="1041"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera48" link="1042"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera49" link="1043"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera50" link="1044"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera51" link="1045"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera52" link="1046"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera53" link="1047"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera54" link="1048"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera55" link="1049"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera56" link="105"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera57" link="1050"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera58" link="1051"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera59" link="1052"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera60" link="1053"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera61" link="1054"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera62" link="1055"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera63" link="1056"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera64" link="1059"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera65" link="106"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera66" link="1060"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera67" link="1061"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera68" link="1062"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera69" link="1063"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera70" link="1064"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera71" link="1065"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera72" link="1066"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera73" link="1067"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera74" link="1068"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera75" link="1069"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera76" link="107"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera77" link="1070"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera78" link="1071"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera79" link="1072"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera80" link="1073"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera81" link="1074"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera82" link="1075"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera83" link="1076"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera84" link="1077"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera85" link="1078"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera86" link="1079"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera87" link="108"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera88" link="1080"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera89" link="1081"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera90" link="1082"/>
<camera class="org.matsim.contrib.smartcity.perception.camera.PassiveCamera" id="camera91" link="1083"/>
